//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use rocket::serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "account")]
#[serde(crate = "rocket::serde")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accounts_characters::Entity")]
    AccountsCharacters,
    #[sea_orm(has_many = "super::accounts_foods::Entity")]
    AccountsFoods,
    #[sea_orm(has_many = "super::accounts_machines::Entity")]
    AccountsMachines,
    #[sea_orm(has_many = "super::accounts_missions::Entity")]
    AccountsMissions,
    #[sea_orm(has_many = "super::business::Entity")]
    Business,
}

impl Related<super::accounts_characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountsCharacters.def()
    }
}

impl Related<super::accounts_foods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountsFoods.def()
    }
}

impl Related<super::accounts_machines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountsMachines.def()
    }
}

impl Related<super::accounts_missions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountsMissions.def()
    }
}

impl Related<super::business::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Business.def()
    }
}

impl Related<super::character::Entity> for Entity {
    fn to() -> RelationDef {
        super::accounts_characters::Relation::Character.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::accounts_characters::Relation::Account.def().rev())
    }
}

impl Related<super::food::Entity> for Entity {
    fn to() -> RelationDef {
        super::accounts_foods::Relation::Food.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::accounts_foods::Relation::Account.def().rev())
    }
}

impl Related<super::machine::Entity> for Entity {
    fn to() -> RelationDef {
        super::accounts_machines::Relation::Machine.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::accounts_machines::Relation::Account.def().rev())
    }
}

impl Related<super::mission::Entity> for Entity {
    fn to() -> RelationDef {
        super::accounts_missions::Relation::Mission.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::accounts_missions::Relation::Account.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
